name: Build and Publish Image to Docker Hub

on: [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build ./front-end-nextjs/ -t docker00789/devops-qr-ui:latest
      - name: push image to docker hub
        run: |
          docker push docker00789/devops-qr-ui:latest
